---
title: "Group6_IB9HP0"
output: html_document
date: "2024-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
```
## Creating a connection to a database

```{r connect}
my_db <- RSQLite::dbConnect(RSQLite::SQLite(),"ecommerce.db")
```


## SQL Database Schema Creation

### ADS
```{sql connection = my_db}
CREATE TABLE ADS(
  AD_ID VARCHAR(30) PRIMARY KEY,
  PLATFORM VARCHAR(255),
  AD_TITLE VARCHAR(255),
  AD_TYPE VARCHAR(70),
  AD_START_DATE DATE,
  AD_END_DATE DATE,
  COST_PER_CLICK FLOAT,
  CLICK_THROUGH_RATE FLOAT,
  NUMBER_OF_CLICKS FLOAT
);
```

### PROMOTION
```{sql connection = my_db}
CREATE TABLE PROMOTION (
  PROMOTION_ID VARCHAR(30) PRIMARY KEY,
  PROMOTION_VALUE FLOAT,
  PROMOTION_START_DATE DATE,
  PROMOTION_END_DATE DATE,
  MINIMUM_PURCHASE_AMOUNT FLOAT
);
```


### CATEGORY
```{sql connection = my_db}
CREATE TABLE CATEGORY(
  CATEGORY_ID VARCHAR(30) PRIMARY KEY,
  CATEGORY_NAME TEXT NOT NULL,
  GENDER TEXT,
  AGE_GROUP VARCHAR(30)
);
```

### SUPPLIER
```{sql connection = my_db}
CREATE TABLE SUPPLIER (
    SUPPLER_ID VARCHAR(30) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(50),
    SUPPLIER_PHONE NUMERIC(10),
    SUPPLIER_POSTCODE VARCHAR(30),
    SUPPLIER_EMAIL VARCHAR(30)
);
```

### CUSTOMERS
```{sql connection=my_db}
CREATE TABLE IF NOT EXISTS CUSTOMERS(
  CUSTOMER_ID VARCHAR(30) PRIMARY KEY,
  AD_ID VARCHAR(30),
  EMAIL_ADDRESS VARCHAR(30),
  PHONE_NUMBER NUMERIC(10),
  CUSTOMER_NAME VARCHAR(30),
  CUSTOMER_GENDER TEXT,
  DATE_OF_BIRTH DATE,
  HOUSE_NUMBER VARCHAR(30),
  POSTCODE VARCHAR(30),
  FOREIGN KEY (AD_ID) REFERENCES ADS (AD_ID)
);
```

### PRODUCT
```{sql connection=my_db}
CREATE TABLE IF NOT EXISTS SKU(
    PRODUCT_ID VARCHAR(30) PRIMARY KEY,
    SUPPLIER_ID VARCHAR(30),
    CATEGORY_ID VARCHAR(30),
    COLOR TEXT,
    UNIT_WEIGHT FLOAT,
    PRODUCT_SELLING_PRICE FLOAT,
    PRODUCT_PURCHASING_PRICE FLOAT,
    BRAND TEXT,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);
```

### TRANSACTION
```{sql connection=my_db}
CREATE TABLE TRANSACTIONS(
  TRANSACTION_ID VARCHAR(30) PRIMARY KEY,
  TRANSACTION_VALUE FLOAT,
  PAYMENT_METHOD VARCHAR(50),
  TRANSACTION_STATUS VARCHAR(50)
);
```


### ORDERS
```{sql connection=my_db}
CREATE TABLE ORDERS (
  ORDER_ID VARCHAR(30) PRIMARY KEY,
  PRODUCT_ID VARCHAR(30),
  CUSTOMER_ID VARCHAR(30),
  TRANSACTION_ID VARCHAR(30),
  ORDER_QUANTITY INTEGER,
  ORDER_DATE DATE,
  ORDER_STATUS TEXT,
  FOREIGN KEY (PRODUCT_ID) REFERENCES SKU(PRODUCT_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
  FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(TRANSACTION_ID)
);
```


### RETURNS

```{sql connection=my_db}
CREATE TABLE RETURNS(
  RETURN_ID VARCHAR(30) PRIMARY KEY,
  PRODUCT_ID VARCHAR(30),
  CUSTOMER_ID VARCHAR(30),
  RETURN_QUANTITY NUMERIC,
  RETURN_DATE DATE,
  RETURN_STATUS TEXT,
  FOREIGN KEY (PRODUCT_ID) REFERENCES SKU(PRODUCT_ID),
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);
```







## Synthetic Data Generation
```{r}
# Set the seed for randomness
set.seed(123) 
```

### Create CATEGORY entity
```{r}
# Define categories, genders, and age groups

CATEGORY_ID <- 10001:10080

# Generate all combinations
CATEGORY <- expand.grid(CATEGORY_NAME, GENDER, AGE_GROUP)
CATEGORY$CATEGORY_ID <- CATEGORY_ID

# Rename columns
names(CATEGORY) <- c("CATEGORY_NAME", "GENDER", "AGE_GROUP", "CATEGORY_ID")

# Remove unrealistic cases
CATEGORY <- CATEGORY[!(CATEGORY$CATEGORY_NAME == 'Dress' & CATEGORY$GENDER == 'Male'), ]

  
```

### Create SUPPLIER data

```{r}
# Define the list of legal entity names with a focus on clothes manufacturers
supplier_names <- c(
  "Vogue Apparel Co",
  "Elite Fashions Inc",
  "Chic Designs Ltd",
  "Trendy Textiles Group",
  "Fashion Forward Creations LLC",
  "StyleMakers International",
  "Elegance Garments Ltd.",
  "Modern Threads Co",
  "Urban Couture Enterprises",
  "Glamour Wear Inc",
  "Fashionista Industries Ltd",
  "Couture Creations LLC",
  "Trendsetter Textiles Inc.",
  "Classic Styles Group",
  "Designer Denim Co.",
  "Boutique Brands Ltd",
  "Luxury Labels International",
  "Chic Couture Creations",
  "Trendy Tailors Inc",
  "Fancy Fabrics Group"
)

# Create SUPPLIER dataframe
SUPPLIER <- data.frame(SUPPLIER_NAME=supplier_names, stringsAsFactors = TRUE)

#Add SUPPLIER_EMAIL
generate_email <- function(company_name) {
  # Convert company name to lowercase and remove spaces
  company_name <- gsub(" ", "", tolower(company_name))
  # Generate email domain based on company name
  domain <- paste0(company_name, ".com")
  # Generate email address
  email <- paste0("customer_service@", domain)
  return(email)
}

SUPPLIER$SUPPLIER_EMAIL <- sapply(supplier_names, generate_email)

### Create random phone number
SUPPLIER$SUPPLIER_PHONE <- paste0("+44", round(runif(nrow(SUPPLIER), min = 10*10, max = 9999999999)))

### Add SUPPLIER_POST_CODE
SUPPLIER$SUPPLIER_POST_CODE <- c(
  "SW1A 1AA",
  "EC1A 1BB",
  "W1A 1HQ",
  "N1C 4AG",
  "SE1 7PB",
  "NW1W 0NY",
  "SW1A 0AA",
  "EC1A 1BB",
  "W1A 1HQ",
  "N1C 4AG",
  "SE1 7PB",
  "NW1W 0NY",
  "SW1A 0AA",
  "EC1A 1BB",
  "W1A 1HQ",
  "N1C 4AG",
  "SE1 7PB",
  "NW1W 0NY",
  "SW1A 0AA",
  "EC1A 1BB"
)

## Add SUPPLIER_ID
SUPPLIER$SUPPLIER_ID = paste0("SP", seq_len(nrow(SUPPLIER)) + 10000)
```


### Create SKU data
```{r}
## Define colors, size, gender, age groups,
colors <- c("black", "white", "blue", "gray", "navy", "red", "green", "brown", "beige", "pink", "purple", "yellow", "orange", "burgundy", "teal")
sizes <- c("XS", "S", "M", "L", "XL")
genders <- c("Male", "Female")
age_groups <- c("Kids", "Pre-Teens", "Young Adults", "Adults")

# Create a dataframe to store all combinations
combinations <- expand.grid(colors = colors,
                            size = sizes,
                            gender = genders,
                            age_group = age_groups,
                            stringsAsFactors = TRUE)

# Define product names for each category
product_names <- list(
  Shirts = c("T-shirt", "Polo shirt", "Button-up shirt", "Blouse", "Sweater"),
  Innerwear = c("Underwear", "Bra"),
  Activewear = c("Hoodie", "Track pants", "Sports tights", "Running shorts"),
  Shoes = c("Sneakers", "Boots", "Sandals"),
  Jackets = c("Coat", "Denim Jacket", "Leather Jacket", "Puffer Jacket"),
  Accessories = c("Gloves", "Necklaces", "Scarf", "Hat", "Ring"),
  Thermals = c("Thermal top", "Thermal bottoms"),
  Pants = c("Joggers", "Cargo Pants", "Chinos", "Sweatpants"),
  Jeans = c("Skinny Jeans", "Straight Leg Jeans", "Flare Jeans"),
  Dress = c("Summer Dress", "Spring Dress", "Winter Dress", "Cocktail Dress")
)

# Create a list to store SKU data
sku_list <- list()

# Iterate over each category and combine with combinations dataframe
for (category in names(product_names)) {
  product_df <- expand.grid(PRODUCT_NAME = product_names[[category]], stringsAsFactors = FALSE)
  product_df$CATEGORY <- category
  sku_list[[category]] <- merge(combinations, product_df, by = NULL)
}

# Combine all SKU dataframes into one dataframe
SKU <- do.call(rbind, sku_list)

# Rename columns
names(SKU) <- c("COLOR", "SIZE", "GENDER", "AGE_GROUP", "PRODUCT_NAME", "CATEGORY")

# Remove unrealistic cases
SKU <- SKU[!(SKU$CATEGORY == 'Dress' & SKU$GENDER == 'Male'), ]
SKU <- SKU[!(SKU$PRODUCT_NAME == 'Bra' & SKU$GENDER == 'Male'), ]

# Add SKU_ID column
SKU$PRODUCT_ID <- paste0("SKU", seq_len(nrow(SKU)) + 10000)

# Add selling and purchasing price
SKU$PRODUCT_PURCHASING_PRICE <- round(runif(nrow(SKU),min=20,max=100),2)
SKU$PRODUCT_PURCHASING_PRICE[SKU$CATEGORY == "Accessories"] <- round(runif(sum(SKU$CATEGORY == "Accessories"), min = 5, max = 20), 2)
markup <- runif(nrow(SKU), min = 0.1, max = 0.3)
SKU$PRODUCT_SELLING_PRICE <- round(SKU$PRODUCT_PURCHASING_PRICE *(1 + markup), 2)

# Add SUPPLIER_ID
SKU$SUPPLIER_ID <- sample(SUPPLIER$SUPPLIER_ID, size = nrow(SKU), replace = TRUE)

```

### Create ORDER data

```{r}
# Create ORDER dataframe
ORDER <- data.frame(
  ORDER_ID = paste0("OD", seq_len(1000) + 10000),
  stringsAsFactors = TRUE
)

# Add ORDER_STATUS:
order_status <- c("Order placed","In transit","Delivered","Cancelled","Returned")
probabilities_order <- c(0.1, 0.35, 0.5, 0.025, 0.025)
ORDER$ORDER_STATUS <- as.factor(sample(order_status, size = nrow(ORDER), replace = TRUE,prob = probabilities_order))


# Add ORDER_DATE
start_date <- as.Date("2023-01-01")
end_date <- as.Date("2023-12-31")
ORDER$ORDER_DATE <- sample(seq(start_date, end_date, by = "day"), nrow(ORDER), replace = TRUE)

# Create an empty dataframe to store order-product mappings
order_product_mapping <- data.frame(ORDER_ID = character(), PRODUCT_ID = character(), stringsAsFactors = FALSE)

# Define the number of products per order
products_per_order <- round(runif(nrow(ORDER), min = 1, max = 10))

# Loop through each order ID and sample products
for (i in 1:nrow(ORDER)) {
  order_id <- ORDER$ORDER_ID[i]
  product_ids <- sample(SKU$PRODUCT_ID, size = products_per_order[i], replace = FALSE)
  order_product_mapping <- rbind(order_product_mapping, data.frame(ORDER_ID = rep(order_id, length(product_ids)), PRODUCT_ID = product_ids))
}

# Merge order_product_mapping with ORDER dataframe to retain other order details
ORDER <- merge(ORDER, order_product_mapping, by = "ORDER_ID", all.x = TRUE)

# Add ORDER_QUANTITY
ORDER$ORDER_QUANTITY <-round(runif(nrow(ORDER),min=1,max=5),0)

# Get summary of ORDER
summary(ORDER)
```

### Create TRANSACTION table

```{r}
# Create TRANSACTION dataframe
TRANSACTION <- data.frame(
  ORDER_ID = unique(ORDER$ORDER_ID),
  stringsAsFactors = TRUE
)

# Add PAYMENT_METHOD
payment_method <- c("Credit card","Debit card","Paypal","Gift Card")
probabilities_payment_method <- c(0.45, 0.35, 0.175, 0.025)
TRANSACTION$PAYMENT_METHOD <- as.factor(sample(payment_method, size = nrow(TRANSACTION), replace = TRUE,prob = probabilities_payment_method))

# Add TRANSACTION_VALUE
## Match ORDER_ID between TRANSACTION and SKU dataframes
mapping <- ORDER%>% left_join(select(SKU, PRODUCT_ID, PRODUCT_SELLING_PRICE), by = "PRODUCT_ID")
## Define discount percents
mapping$discount_percent = runif(nrow(mapping), min = 0, max = 0.2)
## Calculate transaction value
mapping$net_revenue <- mapping$ORDER_QUANTITY*mapping$PRODUCT_SELLING_PRICE*(1-mapping$discount_percent)
transaction_value<- mapping %>%
  group_by(ORDER_ID) %>%
  summarise(TRANSACTION_VALUE = sum(net_revenue))
## Map TRANSACTION_VALUE to TRANSACTION table
TRANSACTION <- left_join(TRANSACTION, transaction_value, by = "ORDER_ID")

# Add PAYMENT_STATUS
## All current order has to have a successful transaction
TRANSACTION$TRANSACTION_STATUS <- "Successful"
## Assume there are 5% of transactions declined
indices_to_duplicate <- sample(1:nrow(TRANSACTION), size = 0.05*nrow(TRANSACTION))
duplicated_failed_transactions <- TRANSACTION[indices_to_duplicate, ]
duplicated_failed_transactions$TRANSACTION_STATUS <- "Declined"
TRANSACTION <- rbind(TRANSACTION, duplicated_failed_transactions)

## Assign TRANSACTION_ID
TRANSACTION$TRANSACTION_ID <- paste0("TR", seq_len(nrow(TRANSACTION)) + 10000)
```


## Data Import and Quality Assurance

