---
title: "Sample"
output: html_document
date: "2024-03-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
```

# Establishing the connection to db
```{r connect}
my_db <- RSQLite::dbConnect(RSQLite::SQLite(),"/cloud/project/ecommerce.db")
```

## Query table for long-term analysis (Por Part)

### Revenue Analysis (Overall Revenue)
```{sql connection = my_db}
SELECT T1.PRODUCT_ID AS PRODUCT_ID,
T2.CATEGORY_ID AS CATEGORY_ID,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD
FROM ORDERS       
GROUP BY ORDERS.PRODUCT_ID
   
) AS T1 

LEFT JOIN 

( SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
         SKU.CATEGORY_ID AS CATEGORY_ID,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
FROM SKU
) AS T2 

ON T1.PRODUCT_ID = T2.PRODUCT_ID

```

```{r Revenue Analysis Table}

Revenue_analysis_df <- RSQLite::dbGetQuery(my_db, 
"SELECT T1.PRODUCT_ID AS PRODUCT_ID,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD
FROM ORDERS       
GROUP BY ORDERS.PRODUCT_ID
   
) AS T1 

LEFT JOIN 

( SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
FROM SKU
) AS T2 

ON T1.PRODUCT_ID = T2.PRODUCT_ID
"
)

```

### Revenue b (Top 10 CATs)

```{sql connection = my_db}

SELECT T3.CATEGORY_ID,
       SUM(T3.UNIT_SOLD) AS TOTAL_UNIT_SOLD,
       SUM(T3.TOTAL_REVENUE) AS TOTAL_REVENUE

FROM
(
SELECT T2.CATEGORY_ID AS CATEGORY_ID,
       T1.PRODUCT_ID AS PRODUCT_ID,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
    ( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD
      FROM ORDERS       
      GROUP BY ORDERS.PRODUCT_ID
   
    ) AS T1 

  LEFT JOIN 

    ( 
    SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
         SKU.CATEGORY_ID AS CATEGORY_ID,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
    FROM SKU
    ) AS T2 

  ON T1.PRODUCT_ID = T2.PRODUCT_ID
  GROUP BY T2.CATEGORY_ID 
) AS T3

GROUP BY T3.CATEGORY_ID


```

```{r Category Revenue Analysis Table}

Category_Analysis_df <- RSQLite::dbGetQuery(my_db, 
"SELECT T3.CATEGORY_ID,
       SUM(T3.UNIT_SOLD) AS TOTAL_UNIT_SOLD,
       SUM(T3.TOTAL_REVENUE) AS TOTAL_REVENUE

FROM
(
SELECT T2.CATEGORY_ID AS CATEGORY_ID,
       T1.PRODUCT_ID AS PRODUCT_ID,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
    ( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD
      FROM ORDERS       
      GROUP BY ORDERS.PRODUCT_ID
   
    ) AS T1 

  LEFT JOIN 

    ( 
    SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
         SKU.CATEGORY_ID AS CATEGORY_ID,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
    FROM SKU
    ) AS T2 

  ON T1.PRODUCT_ID = T2.PRODUCT_ID
  GROUP BY T2.CATEGORY_ID 
) AS T3

GROUP BY T3.CATEGORY_ID"
)

```

### ADS Platform a (Number of customer acquired by each Platform in last 1 year)

```{sql connection = my_db}
SELECT  T3.PLATFORM AS PLATFORM,
        COUNT(T3.PLATFORM) AS CUSTOMER_ACQUIRED_IN_LAST_YEAR
FROM
(
SELECT *
FROM
  (
  SELECT  CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
  ) AS T2

LEFT JOIN

  (
  SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
      
  ) AS T1

ON T1.AD_ID = T2.AD_ID
WHERE T1.PLATFORM IS NOT NULL
) AS T3
GROUP BY T3.PLATFORM

```

```{r Customer by ADS Analysis Table}

Customer_Acquisition_df <- RSQLite::dbGetQuery(my_db, 
"SELECT  T3.PLATFORM AS PLATFORM,
        COUNT(T3.PLATFORM) AS CUSTOMER_ACQUIRED_IN_LAST_YEAR
FROM
(
SELECT *
FROM
  (
  SELECT  CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
  ) AS T2

LEFT JOIN

  (
  SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
      
  ) AS T1

ON T1.AD_ID = T2.AD_ID
WHERE T1.PLATFORM IS NOT NULL
) AS T3
GROUP BY T3.PLATFORM"
)

```

### ADS Platform b (Number of customer acquired by each Platform categorised by gender and age_group ,from the ADS that launch in last 1 year)

```{sql connection = my_db}

SELECT T3.PLATFORM AS PLATFORM,
        T3.CUSTOMER_GENDER AS GENDER,
        AVG(T3.AGE_YEARS) AS AVG_AGES,
        COUNT(DISTINCT T3.CUSTOMER_ID) AS TOTAL_CUSTOMER
FROM
(
SELECT *
FROM
(
SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
  AND ADS.AD_ID IS NOT NULL
) AS T2

LEFT JOIN

(
SELECT CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID,
        CUSTOMERS.CUSTOMER_GENDER,
        ((cast(julianday('now') - julianday(CUSTOMERS.DATE_OF_BIRTH) AS INTEGER))/365)  AS AGE_YEARS
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
) AS T1

ON T2.AD_ID = T1.AD_ID
) AS T3

WHERE T3.CUSTOMER_ID IS NOT NULL
GROUP BY T3.PLATFORM, T3.CUSTOMER_GENDER

```
```{r Customer Acquisition Demographic Analysis Table}

ADS_Customer_Demographic_df <- RSQLite::dbGetQuery(my_db, 
"SELECT T3.PLATFORM AS PLATFORM,
        T3.CUSTOMER_GENDER AS GENDER,
        AVG(T3.AGE_YEARS) AS AVG_AGES,
        COUNT(DISTINCT T3.CUSTOMER_ID) AS TOTAL_CUSTOMER
FROM
(
SELECT *
FROM
(
SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
  AND ADS.AD_ID IS NOT NULL
) AS T2

LEFT JOIN

(
SELECT CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID,
        CUSTOMERS.CUSTOMER_GENDER,
        ((cast(julianday('now') - julianday(CUSTOMERS.DATE_OF_BIRTH) AS INTEGER))/365)  AS AGE_YEARS
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
) AS T1

ON T2.AD_ID = T1.AD_ID
) AS T3

WHERE T3.CUSTOMER_ID IS NOT NULL
GROUP BY T3.PLATFORM, T3.CUSTOMER_GENDER"
)
```     

