rm(list=ls())
library(readr)
library(RSQLite)
library(dplyr)
library(ggplot2)

my_db <- RSQLite::dbConnect(RSQLite::SQLite(),"ecommerce.db")

# Short Term Analysis - Performance of the Organisation in the last 30 days
## Top 10 Most Selling SKU and their corresponding revenue generated

Query_1 <- "WITH PRODUCTS AS(
    SELECT PRODUCT_ID, SALES
    FROM
    (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY SALES DESC) AS row_num
    FROM   
    (
        SELECT PRODUCT_ID, sum(order_quantity) as SALES
        FROM ORDERS
        WHERE DATE(ORDER_DATE) >= date('now','-30 days')
              AND ORDER_STATUS = 'Delivered'
        GROUP BY PRODUCT_ID
    ) T1
    ) T2
    WHERE T2.row_num <= 10
)
SELECT T1.PRODUCT_ID, T2.PRODUCT_NAME, T1.SALES, T1.SALES*T2.SELLING_PRICE AS REVENUE
FROM PRODUCTS T1
LEFT JOIN (
SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME, MARKUP * PRODUCT_PURCHASING_PRICE + PRODUCT_PURCHASING_PRICE AS SELLING_PRICE 
FROM SKU ) T2 
on T1.PRODUCT_ID = T2.PRODUCT_ID"

top_10_SKUs <- RSQLite::dbGetQuery(my_db, Query_1)
top_10_SKUs$name_sku <- paste(top_10_SKUs$PRODUCT_NAME, top_10_SKUs$PRODUCT_ID, sep = "_")

top_10_SKUs$PRODUCT_ID <- factor(top_10_SKUs$PRODUCT_ID, levels = top_10_SKUs$PRODUCT_ID[order(top_10_SKUs$SALES)])


Short_Term_Plot1 <- ggplot(top_10_SKUs, aes(x = reorder(name_sku, REVENUE), y = SALES)) +
  geom_bar(stat = "identity", aes(fill = REVENUE), show.legend = FALSE) +
  labs(x = "Product Names", y = "Units Sold", title = "Top 10 Most Sold SKUs in Units", subtitle = "Labels indicate revenue generated by the SKUs") +
  coord_flip() +
  theme(axis.text.x = element_text(hjust = 1)) + 
  geom_text(aes(label = paste("£",round(REVENUE),sep="")), hjust = 1.05, color='white') + 
  theme(axis.text.x = element_text(hjust = 1, size=6 , vjust = 1), axis.text.y = element_text(angle = 45, size = 6) )

filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/01_Top10_Sold_SKUs_",
              filename_date,"_",
              filename_time,".png"))

Short_Term_Plot1



## Top 10 most returned SKUs

Query_2 <- "WITH PRODUCTS AS(
    SELECT PRODUCT_ID, SALES
    FROM
    (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY SALES DESC) AS row_num
    FROM   
    (
        SELECT PRODUCT_ID, sum(order_quantity) as SALES
        FROM ORDERS
        WHERE DATE(ORDER_DATE) >= date('now','-30 days')
              AND ORDER_STATUS = 'Returned'
        GROUP BY PRODUCT_ID
    ) T1
    ) T2
    WHERE T2.row_num <= 10
)
SELECT T1.PRODUCT_ID, T2.PRODUCT_NAME, T1.SALES, T1.SALES*T2.SELLING_PRICE AS REVENUE
FROM PRODUCTS T1
LEFT JOIN (
SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME, MARKUP * PRODUCT_PURCHASING_PRICE + PRODUCT_PURCHASING_PRICE AS SELLING_PRICE 
FROM SKU ) T2 
on T1.PRODUCT_ID = T2.PRODUCT_ID"

top_10_returned_SKUs <- RSQLite::dbGetQuery(my_db,Query_2)

top_10_returned_SKUs$name_sku <- paste(top_10_returned_SKUs$PRODUCT_NAME,top_10_returned_SKUs$PRODUCT_ID, sep = "_")


top_10_returned_SKUs$PRODUCT_ID <- factor(top_10_returned_SKUs$PRODUCT_ID, levels = top_10_returned_SKUs$PRODUCT_ID[order(top_10_returned_SKUs$SALES)])

Short_Term_Plot2 <- ggplot(top_10_returned_SKUs, aes(x = reorder(PRODUCT_ID, REVENUE), y = as.numeric(SALES))) +
  geom_bar(stat = "identity", aes(fill = REVENUE), show.legend = FALSE) +
  labs(x = "Product Names", y = "Units Returned", title = "Top 10 Most Returned SKUs", subtitle = "Labels indicate the money to be refunded back to the customers") + 
  coord_flip() + 
  theme(axis.text.x = element_text(hjust = 1)) + 
  scale_x_discrete(labels =top_10_returned_SKUs$name_sku) +   
  scale_y_continuous(breaks = seq(0, max(as.numeric(top_10_returned_SKUs$SALES),0 ) , by = 1)) + 
  geom_text(aes(label = paste("£",round(REVENUE),sep="")), color='white', hjust = 1.05)


filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/02_Top10_Returned_SKUs_",
              filename_date,"_",
              filename_time,".png"), dpi = 300, height = 5, width = 7, unit = 'in')

Short_Term_Plot2



## Suppliers who are responsible for the most returned SKUs

faulty_suppliers <- RSQLite::dbGetQuery(my_db,"WITH RankedData as (
SELECT PRODUCT_ID, QUANTITY_RETURNED
FROM
(
  SELECT *,
  ROW_NUMBER() OVER (ORDER BY QUANTITY_RETURNED DESC) AS row_num
  FROM
  (
    SELECT PRODUCT_ID, SUM(RETURN_QUANTITY) AS QUANTITY_RETURNED
    FROM ORDERS
    WHERE DATE(ORDER_DATE) >= date('now','-30 days')
          AND ORDER_STATUS = 'Returned'
    GROUP BY PRODUCT_ID
  ) T1
) T2
WHERE T2.row_num <= 10
)

SELECT SUPPLIER_NAME, COUNT(DISTINCT PRODUCT_ID) AS TOTAL_PRODUCTS,
SUM(QUANTITY_RETURNED) AS QUANTITY_RETURNED,
SUM(COST_INCURRED) AS COST_INCURRED
FROM
(
SELECT T1.PRODUCT_ID, T2.PRODUCT_NAME, T1.QUANTITY_RETURNED, T1.QUANTITY_RETURNED*T2.PRODUCT_PURCHASING_PRICE AS COST_INCURRED,
T2.SUPPLIER_NAME
FROM RankedData T1
LEFT JOIN
(
SELECT DISTINCT PRODUCT_ID, PRODUCT_NAME, (1 + MARKUP) * PRODUCT_PURCHASING_PRICE AS SELLING_PRICE, PRODUCT_PURCHASING_PRICE, TT1.SUPPLIER_ID, TT2.SUPPLIER_NAME
FROM SKU TT1
LEFT JOIN SUPPLIER TT2
ON TT1.SUPPLIER_ID = TT2.SUPPLIER_ID
) T2
ON T1.PRODUCT_ID = T2.PRODUCT_ID
) T3
GROUP BY SUPPLIER_NAME
ORDER BY COST_INCURRED DESC")

  faulty_suppliers$SUPPLIER_NAME <- factor(faulty_suppliers$SUPPLIER_NAME, levels = faulty_suppliers$SUPPLIER_NAME[order(faulty_suppliers$QUANTITY_RETURNED)])
  
  Short_Term_Plot3 <-  ggplot(faulty_suppliers, aes(x = reorder(SUPPLIER_NAME, COST_INCURRED), y = QUANTITY_RETURNED)) +
    geom_bar(stat = "identity", aes(fill = QUANTITY_RETURNED), show.legend = FALSE) +
    labs(x = "Supplier Names", y = "Units Returned", title = "Top Supplier with Most Returned Products", subtitle = "Labels indicate the cost of items from the supplier") + 
    coord_flip() + 
    theme(axis.text.x = element_text(hjust = 1)) + 
    scale_x_discrete(labels =faulty_suppliers$SUPPLIER_NAME) +   
    scale_y_continuous(breaks = seq(0, max(as.numeric(faulty_suppliers$QUANTITY_RETURNED)), by = 1)) + 
    geom_text(aes(label = paste("£",round(COST_INCURRED),sep="")), color='white', hjust = 1.05) +
    theme(axis.text.x = element_text(hjust = 1, size=6 , vjust = 1), axis.text.y = element_text(angle = 45, size = 6) )
  
  filename_date <- as.character(Sys.Date())
  filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
  ggsave(paste0("figures/03_Top_Returned_Supplier_",
                filename_date,"_",
                filename_time,".png"))
  
  Short_Term_Plot3



# Long Term Analysis - Performance of the Organisation in one year period.

## Revenue Generate by product in last 1 year


# Query table from database and store in data frame for visualisation
Revenue_analysis_df <- RSQLite::dbGetQuery(my_db, 
                                           "SELECT T1.PRODUCT_ID AS PRODUCT_ID,
       T2.PRODUCT_NAME AS PRODUCT_NAME,
       T2.SIZE AS SIZE,
       T2.COLOR AS COLOR,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
         ORDERS.ORDER_DATE AS ORDER_DATE,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD
FROM ORDERS
WHERE cast(julianday('now') - julianday(ORDERS.ORDER_DATE) AS INTEGER ) <= 365
GROUP BY ORDERS.PRODUCT_ID
   
) AS T1 

LEFT JOIN 

( SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
         SKU.PRODUCT_NAME AS PRODUCT_NAME,
         SKU.SIZE AS SIZE,
         SKU.COLOR AS COLOR,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
FROM SKU
) AS T2 

ON T1.PRODUCT_ID = T2.PRODUCT_ID"
)

# Top 20 Revenue generate by SKU in the last year

Revenue_analysis_df$PRODUCT_DESCRIPTION <- paste(Revenue_analysis_df$PRODUCT_ID ,Revenue_analysis_df$PRODUCT_NAME, Revenue_analysis_df$SIZE, Revenue_analysis_df$COLOR, sep = " ")

Long_Term_Plot1 <-  ggplot(data= Revenue_analysis_df %>% slice_max(TOTAL_REVENUE, n = 10)  , 
                           aes(x = TOTAL_REVENUE,  y = reorder( PRODUCT_DESCRIPTION, TOTAL_REVENUE )))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aes(fill=TOTAL_REVENUE), show.legend = FALSE) + 
  labs(x = "Revenue", y = "Product ID and Description", title = "10 Best Selling Products in Last 1 Year ", subtitle = "Labels indicate revenue generated by the SKUs") + 
  geom_text(aes(label = paste("£", round(TOTAL_REVENUE),sep="")), color='white', hjust = 1) + theme(axis.text.x = element_text(hjust = 1), axis.text.y = element_text(size=6 ,angle = 45, vjust = 1, hjust=1))


filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/04_Yearly_Revenue_by_SKU_",
              filename_date,"_",
              filename_time,".png"))

Long_Term_Plot1



## Revenue Generate by Category in last 1 year


# Query table from database and store in data frame for visualisation
Category_Analysis_df <- RSQLite::dbGetQuery(my_db, 
                                            "SELECT T4.CATEGORY_ID AS CATEGORY_ID,
       T4.TOTAL_UNIT_SOLD AS TOTAL_UNIT_SOLD,
       T4.TOTAL_REVENUE AS TOTAL_REVENUE,
       T5.CATEGORY_NAME AS CATEGORY_NAME,
       T5.GENDER AS GENDER,
       T5.AGE_GROUP AS AGE_GROUP

FROM

(SELECT T3.CATEGORY_ID,
       SUM(T3.UNIT_SOLD) AS TOTAL_UNIT_SOLD,
       SUM(T3.TOTAL_REVENUE) AS TOTAL_REVENUE

FROM
(
SELECT T2.CATEGORY_ID AS CATEGORY_ID,
       T1.PRODUCT_ID AS PRODUCT_ID,
       T1.UNIT_SOLD AS UNIT_SOLD,
       T2.SELLING_PRICE_PER_UNIT AS SELLING_PRICE,
       T1.UNIT_SOLD * T2.SELLING_PRICE_PER_UNIT AS TOTAL_REVENUE
FROM
    ( SELECT ORDERS.PRODUCT_ID AS PRODUCT_ID,
       SUM(ORDERS.ORDER_QUANTITY) AS UNIT_SOLD,
       ORDERS.ORDER_DATE AS ORDER_DATE
      FROM ORDERS
      WHERE cast(julianday('now') - julianday(ORDERS.ORDER_DATE) AS INTEGER ) <= 365
      GROUP BY ORDERS.PRODUCT_ID
   
    ) AS T1 

  LEFT JOIN 

    ( 
    SELECT SKU.PRODUCT_ID AS PRODUCT_ID,
         SKU.CATEGORY_ID AS CATEGORY_ID,
      SKU.PRODUCT_PURCHASING_PRICE * (1 + SKU.MARKUP) AS SELLING_PRICE_PER_UNIT
    FROM SKU
    ) AS T2 

  ON T1.PRODUCT_ID = T2.PRODUCT_ID
  GROUP BY T2.CATEGORY_ID 
) AS T3

GROUP BY T3.CATEGORY_ID
) AS T4

LEFT JOIN

(SELECT *
FROM CATEGORY) AS T5

ON T4.CATEGORY_ID = T5.CATEGORY_ID"
)

# Top 20 Revenue generate by category in last 1 year
Category_Analysis_df$CATEGORY_DESCRIPTION <- paste(Category_Analysis_df$CATEGORY_NAME, Category_Analysis_df$GENDER, Category_Analysis_df$AGE_GROUP, sep = " ")


Long_Term_Plot2 <- ggplot(data= Category_Analysis_df %>% slice_max(TOTAL_REVENUE, n = 10)  , aes(x = TOTAL_REVENUE,  y = reorder( CATEGORY_DESCRIPTION, TOTAL_REVENUE )))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), aes(fill=TOTAL_REVENUE), show.legend = FALSE) + 
  labs(x = "Revenue", y = "Category Name", title = "10 Best Selling Categories in Last 1 Year ", subtitle = "Labels indicate the revenue generated from category") + 
  geom_text(aes(label = paste("£", round(TOTAL_REVENUE),sep="")), color='white', hjust = 1) +
  theme(axis.text.x = element_text(hjust = 1), axis.text.y = element_text(size=6 ,angle = 45, vjust = 1, hjust=1))



filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/05_Yearly_Revenue_by_Category_",
              filename_date,"_",
              filename_time,".png"))

Long_Term_Plot2


## ADS Platform a (Number of customer acquired by each Platform in last 1 year, separate by quarter)


# Query table from database and store in data frame for visualisation
Customer_Acquisition_df <- RSQLite::dbGetQuery(my_db, 
                                               "SELECT  T3.PLATFORM AS PLATFORM,
        COUNT(T3.PLATFORM) AS CUSTOMER_ACQUIRED_IN_LAST_YEAR,
        T3.QUARTER_AD AS QUARTER_AD
FROM
(
SELECT *
FROM
  (
  SELECT  CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
  ) AS T2

LEFT JOIN

  (
  SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID,
       CASE
        WHEN cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 90 THEN 'Last 90 days'
        WHEN cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) BETWEEN 90 AND 180 THEN '90 to 180 days'
        WHEN cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) BETWEEN 180 AND 270 THEN '180 to 270 days'
        WHEN cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) BETWEEN 270 AND 365 THEN '270 to 365 days'
        ELSE 'More than one year'
       END AS QUARTER_AD
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
      
  ) AS T1

ON T1.AD_ID = T2.AD_ID
WHERE T1.PLATFORM IS NOT NULL
) AS T3
GROUP BY T3.PLATFORM, T3.Quarter_AD"
)

# Customer Acquisition analysis in last 1 year

Long_Term_Plot3 <- ggplot(Customer_Acquisition_df, aes(x = factor(QUARTER_AD, levels = c( "Last 90 days", "90 to 180 days", "180 to 270 days", "270 to 365 days", "More than one year"  )), y = CUSTOMER_ACQUIRED_IN_LAST_YEAR, fill=factor(PLATFORM, levels = c( "Facebook", "Google Ads", "Instagram", "TikTok", "X"  )  ) )) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.75), show.legend = TRUE) +
  geom_text(aes(label = CUSTOMER_ACQUIRED_IN_LAST_YEAR, y = CUSTOMER_ACQUIRED_IN_LAST_YEAR), color='white',vjust = 1.4, hjust = 0.3) + 
  labs(x = "Acquisition Channel", y = "New Customers", title = "Customer Acquisition in Last 1 Year", subtitle = "Labels indicate the number of new customer from each platform") +
  guides(fill = guide_legend(title = "PLATFORM")) + 
  scale_fill_manual(values = c( "#316FF6", "#FBBC05", "#d62976" , "#000000", "#1DA1F2")) + theme(legend.position="bottom")


filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/06_Customer_by_ADS_",
              filename_date,"_",
              filename_time,".png"))

Long_Term_Plot3


## Customer acquisition analysis by each ADS platform categorised by gender in last 1 year


# Query table from database and store in data frame for visualisation
ADS_Customer_Demographic_df <- RSQLite::dbGetQuery(my_db, 
                                                   "SELECT T3.PLATFORM AS PLATFORM,
        T3.CUSTOMER_GENDER AS GENDER,
        AVG(T3.AGE_YEARS) AS AVG_AGES,
        COUNT(DISTINCT T3.CUSTOMER_ID) AS TOTAL_CUSTOMER
FROM
(
SELECT *
FROM
(
SELECT ADS.PLATFORM AS PLATFORM,
       ADS.AD_START_DATE AS AD_START_DATE,
       ADS.AD_ID AS AD_ID
  FROM   ADS
  WHERE  cast(julianday('now') - julianday(ADS.AD_START_DATE) AS INTEGER ) <= 365
  AND ADS.AD_ID IS NOT NULL
) AS T2

LEFT JOIN

(
SELECT CUSTOMERS.CUSTOMER_ID AS CUSTOMER_ID,
        CUSTOMERS.AD_ID AS AD_ID,
        CUSTOMERS.CUSTOMER_GENDER,
        ((cast(julianday('now') - julianday(CUSTOMERS.DATE_OF_BIRTH) AS INTEGER))/365)  AS AGE_YEARS
  FROM    CUSTOMERS
  WHERE AD_ID IS NOT NULL
) AS T1

ON T2.AD_ID = T1.AD_ID
) AS T3

WHERE T3.CUSTOMER_ID IS NOT NULL
GROUP BY T3.PLATFORM, T3.CUSTOMER_GENDER"
)

# Plot analysis for customer acquisition from different ads platform in one year

Long_Term_Plot4 <- ggplot(ADS_Customer_Demographic_df, aes(x= reorder(PLATFORM, desc(TOTAL_CUSTOMER)), y=TOTAL_CUSTOMER, fill=as.factor(GENDER)))+
  geom_bar(stat = "identity", position = position_dodge(width = 0.75)) + 
  geom_text(aes(label = TOTAL_CUSTOMER, y = TOTAL_CUSTOMER), vjust = -0.1) + 
  labs(x = "Acquisition Channel", y = "New Customers", title = "Customer Acquisition by Gender in Last 1 Year", subtitle = "Labels indicate the number of new customer from each platform", fill="GENDER") + 
  scale_fill_manual(values=c("lightblue","steelblue")) 


filename_date <- as.character(Sys.Date())
filename_time <- as.character(format(Sys.time(), format = "%H_%M"))
ggsave(paste0("figures/07_Customer_Gender_by_ADS_",
              filename_date,"_",
              filename_time,".png"))

Long_Term_Plot4
 